name: Pull request raised
on:
  pull_request:
    branches: [main] # CI gets triggered on pull requests to the main branch
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color